Do not require fakeroot when running as root with the asroot option

diff --git a/pacman-7.1.0-add-asroot-option.patch b/pacman-7.1.0-add-asroot-option.patch
--- a/pacman-7.1.0-add-asroot-option.patch
+++ b/pacman-7.1.0-add-asroot-option.patch
@@ -1,5 +1,19 @@
+diff --git a/scripts/libmakepkg/executable/fakeroot.sh.in b/scripts/libmakepkg/executable/fakeroot.sh.in
+index 469ac03a..d87eb8ee 100644
+--- a/scripts/libmakepkg/executable/fakeroot.sh.in
++++ b/scripts/libmakepkg/executable/fakeroot.sh.in
+@@ -28,6 +28,9 @@ source "$MAKEPKG_LIBRARY/util/message.sh"
+ executable_functions+=('executable_fakeroot')
+ 
+ executable_fakeroot() {
++	if (( EUID == 0 && ASROOT)); then
++		return 0
++	fi
+ 	if (( SOURCEONLY || BUILDPKG )); then
+ 		if ! type -p fakeroot >/dev/null; then
+ 			error "$(gettext "Cannot find the %s binary.")" "fakeroot"
 diff --git a/scripts/makepkg.sh.in b/scripts/makepkg.sh.in
-index da69df8b..d7e7aba5 100644
+index da69df8b..cf09bac9 100644
 --- a/scripts/makepkg.sh.in
 +++ b/scripts/makepkg.sh.in
 @@ -79,6 +79,7 @@ SIGNPKG=''
